[package]
name = "jzmatrix-desktop"
version = "0.1.0"
edition = "2021"
rust-version = "1.85.1"
license = "Apache-2.0"

[lib]
name = "jzmatrix_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "=2.0.0", features = [] }

[dependencies]
matrix-core = { path = "../../../crates/matrix-core" }
serde_json = "=1.0.135"
tauri = { version = "=2.0.0", features = [] }
